In [3]:
import os

cwd = os.getcwd()

In [5]:
import pandas as pd


df = pd.read_csv(cwd + '/data/processed/posts_clean_short.csv')

In [6]:
df.head()

Post Link                                              Title  \
0   11227809  Why is processing a sorted array faster than p...   
1     927358  How do I undo the most recent local commits in...   
2    2003505  How do I delete a Git branch locally and remot...   
3     292357  What is the difference between 'git pull' and ...   
4     231767                  What does the "yield" keyword do?   

                                                Body  \
0  <p>Here is a piece of C++ code that shows some...   
1  <p>I accidentally committed the wrong files to...   
2  <h4>Failed Attempts to Delete a Remote Branch:...   
3  <p>What are the differences between <a href="h...   
4  <p>What is the use of the <code>yield</code> k...   

                                                Tags         CreationDate  \
0  <java><c++><performance><cpu-architecture><bra...  2012-06-27 13:51:36   
1           <git><version-control><git-commit><undo>  2009-05-29 18:09:14   
2  <git><version-control><git-branch><git-push><g...  2010-01-05 01:12:15   
3        <git><version-control><git-pull><git-fetch>  2008-11-15 09:51:09   
4                      <python><iterator><generator>  2008-10-23 22:21:11   

           Answer Date  AcceptedAnswerId        id  \
0  2012-06-27 13:56:42          11227902  11227902   
1  2009-05-29 18:13:42            927386    927386   
2  2010-01-05 01:13:55           2003515   2003515   
3  2008-11-15 09:52:40            292359    292359   
4  2008-10-23 22:48:44            231855    231855   

                                                body  score  \
0  <p><strong>You are a victim of <a href="https:...  26621   
1  <h1>Undo a commit &amp; redo</h1>\n<pre class=...  24809   
2  <h1>Executive Summary</h1>\n<pre><code>git pus...  19556   
3  <p>In the simplest terms, <a href="http://git-...  13368   
4  <p>To understand what <code>yield</code> does,...  12259   

                                       complete_text  \
0  why is processing a sorted array faster than p...   
1  how do i undo the most recent local commits in...   
2  how do i delete a git branch locally and remot...   
3  what is the difference between git pull and gi...   
4  what does the yield keyword do what is the use...   

                                     normalized_text  
0  process sort array faster process unsort array...  
1  undo recent local commit git accident commit w...  
2  delet git branch local remot fail attempt dele...  
3  differ git pull git fetch differ git pull git ...  
4  yield keyword use yield keyword python exampl ...

## Criando os targets

In [8]:
def split_tags(tags):
    tags = tags[1:-1]
    tags = tags.split("><")
    
    return tags

In [9]:
df['targets'] = df.Tags.apply(lambda x: split_tags(x))

In [10]:
df['targets']

0       [java, c++, performance, cpu-architecture, bra...
1                [git, version-control, git-commit, undo]
2       [git, version-control, git-branch, git-push, g...
3             [git, version-control, git-pull, git-fetch]
4                           [python, iterator, generator]
                              ...                        
9995             [scala, for-loop, break, tail-recursion]
9996                                    [sql, sql-server]
9997                         [sql, tsql, sql-server-2008]
9998                          [android, for-loop, kotlin]
9999                [java, java-8, java-stream, iterable]
Name: targets, Length: 10000, dtype: object

## 100 Tags mais usadas

In [22]:
def calculateTagsEntries(df):
    count = {}
    
    for tags in df['targets']:
        for tag in tags:
            if(tag not in count.keys()):
                dataTag = {
                    'entries': 1,
                }
                count[tag] = dataTag
            else:
                count[tag]['entries'] += 1
    return count

def sortTags(count):
    return dict(sorted(count.items(), key=lambda item: -item[1]['entries']))

In [24]:
classes = []

def createClassesColumn(df):
    for documentTags in df['targets']:
        wasInDocumentTags = False

        for documentTag in documentTags:
            if(documentTag in MostUsedTags):
                wasInDocumentTags = True
                classes.append(documentTag)
                break
        if(not wasInDocumentTags):
            classes.append('unknown-tag')
    df['class'] = classes    

In [25]:
MostUsedTags = list(sortTags(calculateTagsEntries(df)).keys())[:100]
createClassesColumn(df)

In [87]:
 y = df['class']

In [86]:
y

0              java
1               git
2               git
3               git
4            python
           ...     
9995    unknown-tag
9996            sql
9997            sql
9998        android
9999           java
Name: class, Length: 10000, dtype: object

In [36]:
targets_set = set(MostUsedTags + ['unknown-tag'])

In [37]:
len(targets_set)

101

In [38]:
targets_set

{'.net',
 'ajax',
 'algorithm',
 'android',
 'android-studio',
 'angular',
 'angularjs',
 'arrays',
 'asp.net',
 'asp.net-mvc',
 'bash',
 'branch',
 'c',
 'c#',
 'c++',
 'c++-faq',
 'class',
 'cocoa-touch',
 'collections',
 'command-line',
 'css',
 'database',
 'dataframe',
 'date',
 'datetime',
 'debugging',
 'dictionary',
 'directory',
 'django',
 'docker',
 'dom',
 'eclipse',
 'enums',
 'exception',
 'file',
 'file-io',
 'function',
 'generics',
 'git',
 'git-branch',
 'github',
 'google-chrome',
 'html',
 'http',
 'ios',
 'java',
 'java-8',
 'javascript',
 'jquery',
 'json',
 'language-agnostic',
 'linq',
 'linux',
 'list',
 'loops',
 'macos',
 'multithreading',
 'mysql',
 'node.js',
 'npm',
 'numpy',
 'object',
 'objective-c',
 'oop',
 'pandas',
 'performance',
 'php',
 'postgresql',
 'python',
 'python-3.x',
 'r',
 'reactjs',
 'regex',
 'rest',
 'ruby',
 'ruby-on-rails',
 'security',
 'shell',
 'sorting',
 'sql',
 'sql-server',
 'string',
 'swift',
 'syntax',
 'terminology',
 'ts

In [69]:
def buildMulticlassTestArrays(targets_set, tags):
    entries = []
    for tagList in tags:
        entry = []
        for target in targets_set:
            if(target in tagList):
                entry.append(1)
            else:
                entry.append(0)
        entries.append(entry)
    return entries

In [88]:
words_post = df.normalized_text.apply(lambda x: str(x))

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
vectorizer.fit(words_post)
X = vectorizer.transform(words_post)

In [89]:
import gc

gc.collect()

1970

In [90]:
from sklearn.model_selection import train_test_split
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#y_test = y_test.apply(lambda x: [x])

In [91]:
from sklearn.ensemble import RandomForestClassifier
# rf_model = RandomForestClassifier(max_features="auto", n_jobs=1,random_state=44)
rf_model = RandomForestClassifier(max_features="auto", n_jobs=1,random_state=44)
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=1, random_state=44)

In [96]:
y_pred = rf_model.predict(X_test)
#y_test = buildMulticlassTestArrays(targets_set, y_test)

In [54]:
gc.collect()

168

In [98]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 61 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  0  0]
 [ 0  0  0 ...  0  3  0]
 [ 0  0  1 ...  0  0  0]]
                    precision    recall  f1-score   support

              .net       0.00      0.00      0.00        15
         algorithm       0.00      0.00      0.00         4
           android       0.72      0.86      0.78        71
    android-studio       0.00      0.00      0.00         2
           angular       0.78      0.70      0.74        10
         angularjs       1.00      0.12      0.22         8
            arrays       0.00      0.00      0.00         5
           asp.net       0.00      0.00      0.00         6
       asp.net-mvc       0.00      0.00      0.00         4
              bash       0.62      0.83      0.71        36
            branch       0.00      0.00      0.00         1
                 c       0.60      0.14      0.22        22
                c#       0.58      0.55      0.57       141
   

C:\Users\Vitor\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vitor\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vitor\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
# rf_model.base_estimator_
# rf_model.estimators_
len(rf_model.estimators_)

100

In [21]:
# import pickle
# s = pickle.dumps(rf_model)
# rf_model_2 = pickle.loads(s)

In [22]:
# from joblib import dump, load
# dump(rf_model, 'rf_model.joblib') 

In [52]:
from sklearn.model_selection import cross_val_score
import numpy as np

np.mean(cross_val_score(rf_model, X_train, y_train, cv=5))

C:\Users\Vitor\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


0.63875